---
ID: "5b4b777c-d42b-4dce-877c-768185ad1a0f"
Parent: "389e812a-30eb-46db-8528-5af685847c3d"
Template: "389e812a-30eb-46db-8528-5af685847c3d"
Path: /sitecore/templates/Project/commerce/ProductContainer/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260912T200417Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\crhistian.ramirez@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\crhistian.ramirez@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b13cd4de-227c-48fd-89db-0979c4736df1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\crhistian.ramirez@sitecore.com
    - ID: "d6346556-895e-4f87-8379-4e295c8ae762"
      Hint: Product Source
      Value: OrderCloud Picker
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260912T200454Z
